### ISSUE TITLE
Polish scraping

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/weBlock#11]
- [x] add `argparse` to `scrape_negative` and offer option to specify number of articles analogous to `scrape_positive`
    - [x] scraping with `narticles = 0` doesn't terminate in `scrape_positive`
    - [x] provide default `narticles > 0`
- [x] print progress updates (positive & negative)
- [x] clean / filter data before insertion into positive database
    - the paragraph `\_` has recently appeared in the database, this leads to no words being left after normalization and a topic vector with components `nan` (`nan > 1` → will be the text matcher's favorite text to match)
    - "copyright", "published on date x", etc paragraphs are undesired

**Comment by tiny-fish-T** [comment]
The problem with narticles = 0 comes from the lambda we are using to gather the urls from google news. I think I saw a better way to solve this by using the generator pattern, but I solved it with a quick if block atm.
