### ISSUE TITLE
Logging consistency

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/weBlock#23]
- [x] create dedicated helper module for `server/backend/validator.py`, e.g. `server/helpers/validator.py`
- [ ] add `logging.py`
    - [ ] create functions such as `bold` that wraps strings for bold printing
    - [ ] single source of truth for all strings that are printed anywhere
    - [ ] etc

**Comment by lucasliebe** [comment]
will not be done until project end because of time constraints
