### ISSUE TITLE
Finish summarization, similarity & censorship

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/weBlock#4]
### summarization

- [x] clean up articles before summarizing
- [x] prevent using same url twice
- [x] give option to scrape multiple queries
- [x] give option to set sources

### similarity

- [x] give option to set censoring topic and constrain used summaries to corresponding database entries

### censorship

- [x] find new threshold value (*everybody*)
- [x] improve performance
    - evaluating similarity to all summarizations in database takes too long (limit number of summarizations / pick newest or most relevant ones)
    - shorten summarizations significantly
- [x] if enough time: consider improving censorship formula (*everybody*)

**Comment by tiny-fish-T** [comment]
my idea for how to avoid using every summarization during censorship:

preprocessing:
- gather clusters of summarizations of the same topic
- for every summarization in this topic cluster: calculate its similarity with every other summarization in the cluster
- the summarization with the highest mean similarity is our cluster-boss and is saved separately (or gets a special attribute for identification)

During censorship:
- for every cluster-boss, calculate its similarity with the given paragraph
- the cluster-boss with the highest similarity identifies a topic cluster that is most similar to our paragraph
- for every summarization in the topic cluster: calculate similarity with the given paragraph
- if the mean similarity is above our threshold, the paragraph is censored

Result: we don't calculate similarity with every single summarization, but we aren't overfitting to a singular summarization either

**Comment by jannis-baum** [comment]
@tiny-fish-T i really like the idea and think it's worth trying it out! one concern might be that scores could be different depending on the cluster and the question wether we actually have a cluster that is a remotely good match. how would you go about the initial clustering i.e. determining 'same topic'?
